/* 
 * DialMyCalls API
 *
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dialmycalls

type Accessaccount struct {

	// Unique identifier for this access account.
	Id Uuid `json:"id,omitempty"`

	// The name of the access account.
	Name string `json:"name,omitempty"`

	// The access account email address.
	Email string `json:"email,omitempty"`

	// When the access account was created.
	CreatedAt string `json:"created_at,omitempty"`

	// When the access account was last updated.
	UpdatedAt string `json:"updated_at,omitempty"`
}
