/* 
 * DialMyCalls API
 *
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dialmycalls

type CallRecipient struct {

	// The recipient's first name.
	Firstname string `json:"firstname,omitempty"`

	// The recipient's last name.
	Lastname string `json:"lastname,omitempty"`

	// Miscellaneous information.
	Miscellaneous string `json:"miscellaneous,omitempty"`

	// The recipient's email address.
	Email string `json:"email,omitempty"`

	// The recipient's phone number.
	Phone string `json:"phone,omitempty"`

	// The recipient's phone extension.
	Extension string `json:"extension,omitempty"`

	// Status of the call. Options: live_answer, vm, busy, no_answer, dialing, not_connected, queued
	Status string `json:"status,omitempty"`

	// Duration of the call in seconds.
	Duration int32 `json:"duration,omitempty"`

	// Result from add-on feature.
	AddOn string `json:"add_on,omitempty"`

	// Number of attempts to call was made.
	Attempts string `json:"attempts,omitempty"`

	// Whether the call was successful or not.
	Successful bool `json:"successful,omitempty"`

	// When the recipient was contacted.
	CalledAt string `json:"called_at,omitempty"`
}
