/* 
 * DialMyCalls API
 *
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dialmycalls

type CreateTextParameters struct {

	// (Required)  Name the broadcast.
	Name string `json:"name,omitempty"`

	// (Required)  The keyword id that should be associated with this broadcast.
	KeywordId Uuid `json:"keyword_id,omitempty"`

	// (Required)  List of messages to send (up to 10).
	Messages []string `json:"messages,omitempty"`

	// When the broadcast should be sent. (Ex: 2016-07-25T12:00:00+0000)
	SendAt string `json:"send_at,omitempty"`

	// Should the broadcast go out immediately?
	SendImmediately bool `json:"send_immediately,omitempty"`

	// Also send an email to the contacts?
	SendEmail bool `json:"send_email,omitempty"`

	// Schedule this broadcast as an access account.
	AccessaccountId Uuid `json:"accessaccount_id,omitempty"`

	// The shortcode id that the broadcast will be sent from.
	ShortcodeId Uuid `json:"shortcode_id,omitempty"`

	// Combine all SMS messages into 1 message on the end users device.
	ConcatenateSms bool `json:"concatenate_sms,omitempty"`

	// (Required)  List of contact information that should be sent the broadcast.
	Contacts []ContactAttributes `json:"contacts,omitempty"`
}
