/* 
 * DialMyCalls API
 *
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dialmycalls

type CreateCallParameters struct {

	// (Required)  Name the broadcast.
	Name string `json:"name,omitempty"`

	// (Required)  The caller id that the message should be sent from.
	CalleridId Uuid `json:"callerid_id,omitempty"`

	// (Required)  The recording id of the message that should be played.
	RecordingId Uuid `json:"recording_id,omitempty"`

	// The recording id of the message that should be played on answering machines.  If not supplied the recording_id will be used.  use_amd must be true in order for this feature to work.
	MachineRecordingId Uuid `json:"machine_recording_id,omitempty"`

	// When the broadcast should be sent. (Ex: 2016-07-25T12:00:00+0000)
	SendAt string `json:"send_at,omitempty"`

	// Should the broadcast go out immediately?
	SendImmediately bool `json:"send_immediately,omitempty"`

	// Using answering machine detection?
	UseAmd bool `json:"use_amd,omitempty"`

	// Also send an email to the contacts?
	SendEmail bool `json:"send_email,omitempty"`

	// Schedule this broadcast as an access account.
	AccessaccountId Uuid `json:"accessaccount_id,omitempty"`

	// (Required)  List of contact information that should be sent the broadcast.
	Contacts []ContactAttributes `json:"contacts,omitempty"`

	// A list of feature add-ons for the calls.
	AddOns []PushToListenAgain `json:"add_ons,omitempty"`
}
