/* 
 * DialMyCalls API
 *
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dialmycalls

type Service struct {

	// Unique identifier for this service.
	Id Uuid `json:"id,omitempty"`

	// Unique identifier for the access account which initiated this if available.
	AccessaccountId Uuid `json:"accessaccount_id,omitempty"`

	// The name of the service.
	Name string `json:"name,omitempty"`

	// Whether the service has been flagged to be cancelled.
	PendingCancel bool `json:"pending_cancel,omitempty"`

	// The amount of credits required to schedule this service.
	CreditCost float32 `json:"credit_cost,omitempty"`

	// The amount of recipients for this service.
	TotalRecipients float32 `json:"total_recipients,omitempty"`

	// When the service will be sent.
	SendAt string `json:"send_at,omitempty"`

	// When the service was created.
	CreatedAt string `json:"created_at,omitempty"`

	// When the service was last updated.
	UpdatedAt string `json:"updated_at,omitempty"`
}
