/* 
 * DialMyCalls API
 *
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dialmycalls

type UpdateVanityNumberByIdParameters struct {

	// The options to include when the number is called.  If an option is not included it will be turned off.  Option values should be boolean.  Possible values are: 'voicemail' (Leave A Message), 'ptt' (Push To Talk), 'optin' (Opt-In), 'repeat' (Repeat Your Message) -- Note: Optout cannot be removed without prior authorization.  Please contact customer support for this.
	CallOptions []string `json:"call_options,omitempty"`

	// Where the recording will be generated from.  (specific, lastsent, lastuploaded)
	RecordingSource string `json:"recording_source,omitempty"`

	// Unique identifier for the recording if recording_source is set to specific.
	SpecificRecordingId Uuid `json:"specific_recording_id,omitempty"`

	// Setting this to true our system will play the prompts for keys to be pushed.
	PlayCta bool `json:"play_cta,omitempty"`

	// This is a verified caller id that is on your account.  This will be used if PTT option is used.
	PttNumberId Uuid `json:"ptt_number_id,omitempty"`
}
